[package]
name = "rlox_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1"
lazy_static = "1.4.0"
thiserror = "1"
ustr = "0.10.0"
